# Default values for supermario-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pengbai/docker-supermario
  pullPolicy: IfNotPresent
  tag: ""

containers:
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080
  target-port: 8080
