name: Build and Push Docker Image

on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker para aceitar registries inseguros
        run: |
          echo '{ "insecure-registries":["${{ secrets.DOCKER_REGISTRY_IP }}"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login no Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_IP }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY_IP }}/supermario:latest .

      - name: Push da imagem para o Registry
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY_IP }}/supermario:latest
